name: SonarCloud
on:
  push:
    branches:
      - master
      - dev-tobi
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v2.4.0
        with:
          java-version: '11'
      - name: Analyze with SonarCloud
        run: mvn -B verify sonar:sonar -Dsonar.junit.reportPaths=$(find "$(pwd)" -path 'surefire-reports/TEST-*.xml' | sed 's/.*/&/' | tr '\n' ',') -Dsonar.coverage.jacoco.xmlReportPaths=$(find "$(pwd)" -path '*jacoco.xml' | sed 's/.*/&/' | tr '\n' ',') -Dsonar.projectKey=tobi6112_demoproject -Dsonar.organization=tobi6112 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}